version: "3"

networks:
  proxy:
    external: true

services:
  
  backend:
    image: registry.mikael.green/mikael.green:latest
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.mikaelgreen.rule=Host(`mikael.green`)
        - traefik.http.routers.mikaelgreen.entrypoints=websecure
        - traefik.http.routers.mikaelgreen.tls=true
        - traefik.http.routers.mikaelgreen.tls.certresolver=le
        - traefik.http.services.mikaelgreen_backend.loadbalancer.server.port=8080
