backend:
  name: gitlab
  repo: skaramicke/mikael.green
  branch: main
  auth_type: implicit
  app_id: 579f03db4c8dcab31eb03b4f69a897d59d9c9e7f2505591e97d80cb0cb474a8b

media_folder: '/src/photos'
public_folder: '/photos'

collections:
  - name: post
    label: Posts
    folder: '/src/posts'
    create: true
    extension: json
    format: json
    fields:
      
      - name: title
        label: Title
      
      - name: date
        label: Date
        widget: datetime
      
      - name: images
        label: Images
        widget: list
        fields: 
          - name: image
            label: Image
            widget: image
       
    slug: '{{year}}-{{month}}-{{day}} {{hour}}:{{minute}}'
