name: Get on the Swarm already

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_URL }}/mikaelgreen:latest .
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/mikaelgreen:latest

      - name: Deploy
        uses: gronitab/docker-swarm-deploy-action@v3
        with:
          remote_host: ${{ secrets.DOCKER_SWARM_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_known_hosts: ${{ secrets.DOCKER_SSH_KNOWN_HOSTS }}
          args: stack deploy --compose-file /github/workspace/deployment.yml mikaelgreen
